# dynamo_memory.py
# Handles reading and writing conversation history to DynamoDB.
#
# Each conversation session is stored as a single DynamoDB item:
#   {
#     "session_id": "abc-123-def-456",      ← primary key (partition/hash key)
#     "messages": [                          ← full conversation history
#       {"role": "user",      "content": "Hello",    "timestamp": "2026-04-09T10:00:00"},
#       {"role": "assistant", "content": "Hi there!", "timestamp": "2026-04-09T10:00:01"}
#     ],
#     "updated_at": "2026-04-09T10:00:01",  ← human-readable last-update time
#     "ttl": 1746000000                     ← Unix timestamp; DynamoDB auto-deletes after this
#   }
#
# This module replaces the S3 JSON file approach from Activity 03.
# DynamoDB is faster (single-digit millisecond reads), cheaper at this scale,
# and supports automatic expiry via TTL so old sessions clean themselves up.

import boto3
import os
from datetime import datetime, timedelta
from typing import List, Dict

# Module-level variables for the DynamoDB resource and Table object.
# None initially — they are created the first time _get_table() is called ("lazy init").
# Once created, they are reused for every subsequent call in the same Lambda
# execution environment (i.e., across warm invocations — no re-initialisation cost).
_dynamodb = None
_table = None


def _get_table():
    """
    Lazily initialise and return the DynamoDB Table object.

    Lazy initialisation means: don't create the connection at import time.
    Wait until the first actual database call, then create it and cache it.

    Why does this matter for Lambda?
    ---------------------------------
    A Lambda "cold start" happens when AWS spins up a fresh execution environment
    for your function (first invocation, or after a period of inactivity).

    During a cold start, Python imports all your modules. If we created the
    DynamoDB client at module-level (outside a function), that network connection
    attempt would run on EVERY cold start — even for requests that never touch
    DynamoDB. With lazy init, the cost is paid only on the first DynamoDB call.

    A Lambda "warm start" happens when an existing execution environment handles
    a new request. The module-level _table variable survives between warm invocations.
    So the second request, third request, etc. skip the initialisation entirely
    and call DynamoDB directly — much faster.
    """
    global _dynamodb, _table
    if _table is None:
        # boto3.resource gives a higher-level, more Pythonic API than boto3.client.
        # It automatically converts Python types to DynamoDB types and back:
        #   Python list of dicts → DynamoDB List of Maps (no manual serialisation needed)
        _dynamodb = boto3.resource("dynamodb", region_name=os.getenv("AWS_REGION", "us-east-1"))

        # DYNAMODB_TABLE is set by Terraform in lambda.tf environment variables.
        # The fallback "twin-dev-conversations" matches the default workspace name.
        table_name = os.getenv("DYNAMODB_TABLE", "twin-dev-conversations")
        _table = _dynamodb.Table(table_name)
    return _table


def load_conversation(session_id: str) -> List[Dict]:
    """
    Load the conversation history for a given session from DynamoDB.

    Returns the list of message dicts if the session exists,
    or an empty list [] if this is a new session or any error occurs.

    DynamoDB get_item does a direct key lookup — it either finds the item
    or it doesn't. There is no partial match or scan involved.

    Parameters:
        session_id: the unique identifier for this conversation
                    (generated by uuid.uuid4() in server.py on the first request)
    """
    try:
        table = _get_table()

        # get_item fetches a single item by its primary key.
        # Key must contain the hash_key declared in storage.tf (session_id: string).
        response = table.get_item(Key={"session_id": session_id})

        # "Item" is present in the response only if DynamoDB found a matching item.
        # If this session_id has never been saved before, "Item" will not be in the response.
        if "Item" in response:
            # Return the messages list. .get() with default [] protects against the
            # unlikely case where the item exists but somehow has no "messages" field.
            return response["Item"].get("messages", [])
        else:
            return []  # Brand new session — no conversation history yet

    except Exception as e:
        # Log the error to CloudWatch Logs so we can debug it,
        # but return [] so the chat endpoint can still respond (without memory context).
        print(f"Error loading conversation from DynamoDB: {e}")
        return []


def save_conversation(session_id: str, messages: List[Dict]) -> None:
    """
    Save (or overwrite) the full conversation history for a session to DynamoDB.

    DynamoDB put_item is an "upsert": it creates the item if it doesn't exist,
    or replaces it entirely if it does. We always pass the complete messages list,
    so overwriting is correct — we're not appending, we're replacing.

    TTL is recalculated on every save, so each conversation gets a rolling 30-day
    expiry from the last message. A frequently-used session will never expire mid-chat.

    Parameters:
        session_id: the unique conversation identifier
        messages:   the full list of message dicts (all turns, including the new ones)
    """
    try:
        table = _get_table()

        # TTL: 30 days from now as a Unix timestamp (integer seconds since epoch).
        # DynamoDB compares this against the current time and deletes the item
        # once the timestamp is in the past. No Lambda code or cron job needed.
        ttl_timestamp = int((datetime.utcnow() + timedelta(days=30)).timestamp())

        # put_item writes the entire item. boto3.resource handles the Python→DynamoDB
        # type conversion automatically: a Python list of dicts becomes a DynamoDB
        # List of Maps with no extra code needed.
        table.put_item(Item={
            "session_id":  session_id,
            "messages":    messages,                          # Full conversation history
            "updated_at":  datetime.utcnow().isoformat(),    # ISO 8601 for human readability
            "ttl":         ttl_timestamp                     # Auto-expiry after 30 days
        })

    except Exception as e:
        # Log the error but don't crash — the user's response was already generated.
        # A failed save means the session won't persist, but the current reply still goes out.
        print(f"Error saving conversation to DynamoDB: {e}")
